spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toyswap
    driver-class-name: org.postgresql.Driver
    username: admin
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  flyway:
    enabled: false

  security:
    user:
      name: admin
      password: pass

app:
  jwt:
    secret: toyswap-application-2023
    expiration: 86400000
